### ISSUE TITLE
"CINNAMOM SCREENSHOTS"

### ISSUE THREAD

**Issue by kylagit** [AERegeneratel38/RicerKit#2]
![_20210424_134128](https://user-images.githubusercontent.com/44444510/115958997-d1e61800-a501-11eb-82ee-f8b3c67ddbb9.JPG)
When you open the app and tap cinnamon, it says "CINNAMOM SCREENSHOTS" at the top

**Comment by kylagit** [comment]
It also says "Cinnamom" on the home page of the app aswell

**Comment by Regenerate38** [comment]
Yeah I have realized the typos. I will take care of it in new release.
